import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from style import apply_global_style
apply_global_style()

st.title("⚠️ Risk Analytics")

st.markdown("""
Employees were segmented into **Low Risk**, **Medium Risk**, and **High Risk**
categories based on attrition probabilities generated by the Random Forest model.
""")

# =====================================================
# DATA
# =====================================================

risk_df = pd.DataFrame(
{
    "Risk Level": [
        "Low Risk",
        "Medium Risk",
        "High Risk"
    ],
    "Employees": [
        6009,
        5519,
        3372
    ]
}
)

total_employees = risk_df["Employees"].sum()

high_risk_pct = round(
    (3372 / total_employees) * 100,
    1
)

# =====================================================
# CSS
# =====================================================

st.markdown("""
<style>

.card {
    background-color: #1F2937;
    padding: 24px;
    border-radius: 12px;
    margin-bottom: 20px;
    border-left: 4px solid #7C93C3;
}

.card-title {
    font-size: 24px;
    font-weight: 700;
    margin-bottom: 12px;
}

</style>
""", unsafe_allow_html=True)

# =====================================================
# KPI SECTION
# =====================================================

st.subheader("Workforce Risk Overview")

col1, col2, col3 = st.columns(3)

with col1:
    st.metric(
        "Total Employees",
        f"{total_employees:,}"
    )

with col2:
    st.metric(
        "High Risk Employees",
        f"{3372:,}"
    )

with col3:
    st.metric(
        "High Risk %",
        f"{high_risk_pct}%"
    )

st.divider()

# =====================================================
# GRAPH
# =====================================================

st.subheader("Employee Risk Segmentation")

fig, ax = plt.subplots(figsize=(8, 4))

sns.barplot(
    data=risk_df,
    x="Risk Level",
    y="Employees",
    #palette=["#7FB3D5", "#F4D03F", "#EC7063"],
    palette= "Blues_r",
    #palette=  ["#14B8A6", "#2DD4BF", "#99F6E4"],
    ax=ax
)

ax.set_title(
    "Employee Risk Distribution",
    fontsize=14,
    fontweight="bold"
)

ax.set_xlabel(
    "Risk Category",
    fontsize=12,
    fontweight="bold"
)

ax.set_ylabel(
    "Number of Employees",
    fontsize=12,
    fontweight="bold"
)

ax.tick_params(
    axis="y",
    labelsize=12.5
)

ax.tick_params(
    axis="x",
    labelsize=12.5
)

for container in ax.containers:
    ax.bar_label(
        container,
        fmt="%d",
        fontsize=10,
        fontweight="bold"
    )

plt.tight_layout()

st.pyplot(fig)

# =====================================================
# TABLE
# =====================================================

st.subheader("Risk Distribution")

st.dataframe(
    risk_df,
    use_container_width=True
)

# =====================================================
# KEY FINDINGS
# =====================================================

st.markdown("""
<div class="card">

<div class="card-title">
📊 Key Findings
</div>

<ul style="line-height:1.8">

<li><b>6,009 employees</b> are categorized as Low Risk.</li>

<li><b>5,519 employees</b> fall into the Medium Risk segment.</li>

<li><b>3,372 employees</b> are classified as High Risk.</li>

<li>Approximately <b>23%</b> of employees require proactive retention attention.</li>

<li>The organization has a significant population of employees who may be at risk of leaving.</li>

</ul>

</div>
""", unsafe_allow_html=True)

# =====================================================
# HIGH RISK PROFILE
# =====================================================

st.markdown("""
<div class="card">

<div class="card-title">
🔍 High-Risk Employee Profile
</div>

<ul style="line-height:1.8">

<li>Typically younger than the organizational average.</li>

<li>Often report lower Work-Life Balance.</li>

<li>More commonly found in lower Job Levels.</li>

<li>Tend to live farther from the workplace.</li>

<li>Usually have shorter organizational tenure.</li>

<li>May have limited access to Remote Work opportunities.</li>

</ul>

</div>
""", unsafe_allow_html=True)

# =====================================================
# HR RECOMMENDATIONS
# =====================================================

st.markdown("""
<div class="card">

<div class="card-title">
💼 Recommended HR Actions
</div>

<ul style="line-height:1.8">

<li>Develop clear career growth and promotion pathways.</li>

<li>Improve employee engagement and recognition programs.</li>

<li>Expand flexible and hybrid work opportunities.</li>

<li>Reduce commuting burden wherever possible.</li>

<li>Strengthen onboarding and mentoring initiatives.</li>

<li>Prioritize retention strategies for High-Risk employees.</li>

</ul>

</div>
""", unsafe_allow_html=True)